### ISSUE TITLE
同样的遭遇> > > ```

### ISSUE THREAD

**Issue by zhangyupy** [parzulpan/real-live#12]
> > > ```
> > > I'm Linux
> > > system_platform:  Linux
> > > system_platform:  Linux
> > > Traceback (most recent call last):
> > >   File "real_live.py", line 36, in <module>
> > >     run()
> > >   File "/home/hu/Code/Python/real-live/src/real-live-desktop/utils/singleton.py", line 24, in inner
> > >     _instance[cls] = cls()
> > >   File "real_live.py", line 29, in run
> > >     main_window = MainWindow()
> > >   File "/home/hu/Code/Python/real-live/src/real-live-desktop/widgets/main_widget.py", line 157, in __init__
> > >     self.vlc_widget = VlcPlayerWidget()
> > >   File "/home/hu/Code/Python/real-live/src/real-live-desktop/widgets/vlc_player_widget.py", line 51, in __init__
> > >     self.set_media_player(args)
> > >   File "/home/hu/Code/Python/real-live/src/real-live-desktop/widgets/vlc_player_widget.py", line 94, in set_media_player
> > >     self.instance = vlc.Instance(*args)
> > >   File "/home/hu/.local/lib/python3.8/site-packages/vlc.py", line 1906, in __new__
> > >     return libvlc_new(len(args), args)
> > >   File "/home/hu/.local/lib/python3.8/site-packages/vlc.py", line 4705, in libvlc_new
> > >     _Cfunction('libvlc_new', ((1,), (1,),), class_result(Instance),
> > >   File "/home/hu/.local/lib/python3.8/site-packages/vlc.py", line 292, in _Cfunction
> > >     raise NameError('no function %r' % (name,))
> > > NameError: no function 'libvlc_new'
> > > ```
> > 
> > 用的什么Python版本？
> python 3.8.2 系统 ubuntu 20.04
> 

建议使用3.6和3.7版本，版本太新，有的库匹配的不是很好。

_Originally posted by @parzulpan in https://github.com/parzulpan/real-live/issue_comments/702462590_

**Comment by zhangyupy** [comment]
我用的是python3.6也会报这样的错误
