### ISSUE TITLE
[Bug]macos运行stable出现ctypes.ArgumentError: argument 2: <class 'TypeError'>: wrong type

### ISSUE THREAD

**Issue by imzhangkebetter** [parzulpan/real-live#13]
Traceback (most recent call last):
  File "real_live.py", line 36, in <module>
    run()
  File "/Users/jackrobin/source/js/real-live/src/real-live-desktop/utils/singleton.py", line 24, in inner
    _instance[cls] = cls()
  File "real_live.py", line 29, in run
    main_window = MainWindow()
  File "/Users/jackrobin/source/js/real-live/src/real-live-desktop/widgets/main_widget.py", line 157, in __init__
    self.vlc_widget = VlcPlayerWidget()
  File "/Users/jackrobin/source/js/real-live/src/real-live-desktop/widgets/vlc_player_widget.py", line 51, in __init__
    self.set_media_player(args)
  File "/Users/jackrobin/source/js/real-live/src/real-live-desktop/widgets/vlc_player_widget.py", line 108, in set_media_player
    self.media_player.set_nsobject(self.media_player_frame.winId())
  File "/Users/jackrobin/source/js/real-live/venv/lib/python3.8/site-packages/vlc.py", line 3709, in set_nsobject
    return libvlc_media_player_set_nsobject(self, drawable)
  File "/Users/jackrobin/source/js/real-live/venv/lib/python3.8/site-packages/vlc.py", line 6835, in libvlc_media_player_set_nsobject
    return f(p_mi, drawable)
ctypes.ArgumentError: argument 2: <class 'TypeError'>: wrong type

**Comment by imzhangkebetter** [comment]
有谁遇到了

**Comment by imzhangkebetter** [comment]
我的是python3.8的环境

**Comment by parzulpan** [comment]
开发环境吗？目前 macOS 版本需要安装 VLC 播放器。
